version: '3.4'

services:

# Database container settings
  database:
    hostname: "MicrosoftSqlServer"
    container_name: "MicrosoftSqlServer"
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "DatabasePassword123"
      ACCEPT_EULA: "Y"

# Service container settings
  witchblades.backend.api:
    hostname: "WitchbladesAPI"
    container_name: "WitchbladesAPI"
    image: ${DOCKER_REGISTRY-}witchbladesbackendapi
    build:
      context: .
      dockerfile: src/Witchblades.Backend/Witchblades.Backend.Api/Dockerfile
    environment:
      ConnectionStrings:WitchbladesContext: "Server=MicrosoftSqlServer;Database=WitchbladesDB;User Id=sa;Password=DatabasePassword123;"
    depends_on:
      - database