version: '3.4'

services:

# Database container
  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"

# Service container
  backend:
    image: ${DOCKER_REGISTRY-}witchbladesbackendapi
    depends_on:
      - database

# Reverse proxy container
  proxy:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - backend